[package]
name = "rkill"
version = "0.1.0"
authors = ["SachinMaharana <sachin.nicky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2.0"
rand = "0.8.3"
skim = "0.9.4"
sysinfo = "0.16.3"
